.TH CPIDX 8 "12 September 1995"
.FB
.SH NAME
cpidx \- copy a \fIFirstBase\fP index to a new file name
.SH SYNOPSIS
.B cpidx
\fIsource_index\fP \fIdestination_index\fP
.SH DESCRIPTION
.I Cpidx 
is a simple shell script that copies a \fIFirstBase\fP index and all
necessary support files to a new destination. The copy is done
interactively using the \fB-i\fP option of cp(1).
\fICpidx\fP will ask permission to destroy existing files.
.PP
Formally, three files are copied: the index itself, the index
header file,
and the index header file. The source files are not removed.
.SH FILES
.PD 0
.TP 10
*.idx
\fIFirstBase\fP index.
.TP 10
*.idict
\fIFirstBase\fP index header file.
.TP 10
*.idicti
\fIFirstBase\fP index dictionary.
.PD
.SH SEE ALSO
cp(1), firstbase(5), dictionaries(5), mvidx(8), rmidx(8)
.PP
.I FirstBase User's Guide and Reference Manual
.br
