.TH INTRO 1 "21 September 1995"
.SH NAME
Intro \- introduction to \fIFirstBase\fP commands
.SH DESCRIPTION
.LP
Section 1 describes \fIFirstBase\fP commands. Most commands begin with
\fBdb\fP or \fBfb\fP. Database dictionary editors all begin with \fBdbd\fP,
and data object generators are of the form \fBdb?gen\fP. These commands are all
executable from the command line. Most require a valid \fIFirstBase\fP
database dictionary.
.SH SEE ALSO
.I FirstBase User's Guide and Reference Manual
.br
Intro(5).
.ne 10
.SH LIST OF FIRSTBASE COMMANDS
.sp 1
.if t .ta 25n +20n
.if n .ta 20n +20n
.nf
.ta 20n +20n
Name 	Appears on Page	Description
.sp 0.10i
dbawk	dbawk(1)	\fIFirstBase\fP pattern scanning and processing language
dbcat	dbcat(1)	concatenate \fIFirstBase\fP databases
dbcgen	dbcgen(1)	generate a converted \fIFirstBase\fP database
dbclean	dbclean(1)	clean a \fIFirstBase\fP database and create a map file
dbdbas	dbdbas(1)	define a \fIFirstBase\fP database dictionary
dbdcnv	dbdcnv(1)	define a \fIFirstBase\fP database conversion dictionary
dbdind	dbdind(1)	define a \fIFirstBase\fP index generator dictionary
dbdlbl	dbdlbl(1)	define a \fIFirstBase\fP label dictionary
dbdmrg	dbdmrg(1)	visual merge editor based on \fIvi\fP(1)
dbdprt	dbdprt(1)	define a \fIFirstBase\fP printout dictionary
dbdscr	dbdscr(1)	define a \fIFirstBase\fP database screen dictionary
dbdupd	dbdupd(1)	define a \fIFirstBase\fP database update dictionary
dbedit	dbedit(1)	full screen \fIFirstBase\fP database editor
dbemit	dbemit(1)	emit a database in comma separated format
dbfilter	dbfilter(1)	filter a new index from an existing index
dbigen	dbigen(1)	generate a \fIFirstBase\fP index
dbjoin	dbjoin(1)	join two \fIFirstBase\fP databases
dblgen	dblgen(1)	generate a set of \fIFirstBase\fP labels
dbload	dbload(1)	load comma separated values into a database
dbls	dbls(1)	list all \fIFirstBase\fP databases and files in a directory
dbmacro	dbmacro(1)	\fIFirstBase\fP macro language processor
dbmerge	dbmerge(1)	merge source text with a  database (mail merge)
dbpack	dbpack(1)	remove deleted records from a \fIFirstBase\fP database
dbpasswd	dbpasswd(1)	allow changes to a \fIFirstBase\fP password
dbpgen	dbpgen(1)	generate a \fIFirstBase\fP tabular printout
dbregen	dbregen(1)	regenerate indexes for a \fIFirstBase\fP database.
dbrload	dbload(1)	replacement/load comma separated values into a database
dbscan	dbedit(1)	full screen \fIFirstBase\fP database scanner (read only)
dbshell	dbshell(1)	the \fIFirstBase\fP menu shell tool
dbshelltool	dbshelltool(1)	the \fIFirstBase\fP window shell
dbsql	dbsql(1)	\fIFirstBase\fP Structured Query Language (SQL)
dbugen	dbugen(1)	generate updates within a \fIFirstBase\fP database
dbundo	dbundo(1)	globally undo all deletions in a database
dbvedit	dbedit(1)	\fIFirstBase\fP visual database editor
dbvemit	dbvemit(1)	visual database emitter \(em dbvedit/dbemit fusion
dbvform	dbvform(1)	format a database using a standard view dictionary
dbvscan	dbedit(1)	\fIFirstBase\fP visual database scanner (read only)
fbez	fbez(1)	run \fIFirstBase EZ-Instructional\fP menu shell
fbfwho	fbfwho(1)	list current users of a \fIFirstBase\fP floating license
firstbase	firstbase(1)	run \fIFirstBase\fP menu shell
frmprint	scrprint(1)	provide menu interface for printing
scrprint	scrprint(1)	provide menu interface for viewing and printing
.fi
.br
