.TH INTRO 5 " 5 April 1996"
.SH NAME
Intro \- file formats and interface mechanisms used by \fIFirstBase\fP programs
.SH DESCRIPTION
.LP
This section describes the format of \fIFirstBase\fP interface files, as
well as other generalized interface mechanisms used within \fIFirstBase\fP.
.SH LIST OF FILE FORMATS AND INTERFACE MECHANISMS
.sp 1
.if t .ta 25n +20n
.if n .ta 20n +20n
.nf
.ta 20n +20n
Name 	Appears on Page	Description
.sp 1
autoindex	autoindex(5)	\fIFirstBase\fP automatic index maintenance
choice	choice(5)	choice file for data entry
coname	coname(5)	the company name file
ddict	ddict(5)	\fIFirstBase\fP database dictionary file
defaults	defaults(5)	\fIFirstBase\fP defaults
dictionaries	dictionaries(5)	\fIFirstBase\fP dictionaries
error	error(5)	List of \fIFirstBase\fP error numbers
firstbase	firstbase(5)	FirstBase Relational Database Management System
generators	generators(5)	\fIFirstBase\fP generators 
idicti	idicti(5)	\fIFirstBase\fP index dictionary files
input	input(5)	Overview of \fIFirstBase\fP input mechanism
keyboard	keyboard(5)	\fIFirstBase\fP keyboard map file
macro	macro(5)	macro definition/script file
printouts	printouts(5)	overview of \fIFirstBase\fP printouts (reports)
screens	screens(5)	\fIFirstBase\fP Screen Overview
setup	setup(5)	the setup (rc) file
terminals	terminals(5)	\fIFirstBase\fP Terminal Overview
view dictionaries	view(5)	\fIFirstBase\fP view dictionaries
visual/filter	visual(5)	the visual and filter files
xchoice	xchoice(5)	extended choice file for data entry
.fi
.br
