.TH MVIDX 8 "12 September 1995"
.FB
.SH NAME
mvidx \- move a \fIFirstBase\fP index to a new file name
.SH SYNOPSIS
.B mvidx
\fIsource_index\fP \fIdestination_index\fP
.SH DESCRIPTION
.I Mvidx
is a simple shell script that moves a \fIFirstBase\fP index and all
necessary support files to a new destination. The move is done
interactively using the \fB-i\fP option of \fImv\fP(1).
\fIMvidx\fP will ask permission to destroy existing files.
.PP
Formally, three files are moved: the index itself, the index
dictionary, and the index header file. The source files are actually
just renamed \(em no copying takes place.
.SH FILES
.PD 0
.TP 10
*.idx
\fIFirstBase\fP index.
.TP 10
*.idict
\fIFirstBase\fP index header file.
.TP 10
*.idicti
\fIFirstBase\fP index dictionary.
.PD
.SH SEE ALSO
mv(1), firstbase(5), dictionaries(5), cpidx(8), rmidx(8)
.PP
.I FirstBase User's Guide and Reference Manual
.br
