.TH TRIM 3 "12 September 1995"
.FB
.SH NAME
rmlead \- remove leading blanks of a string
.SH SYNOPSIS
char *fb_rmlead(s)
.br
char *s;
.PP
.SH DESCRIPTION
\fIFb_rmlead\fP is a simple routine in the \fIFirstBase\fP library used to
remove leading blanks from any NULL terminated string.
.PP
\fIFb_rmlead\fP returns the argument \fIs\fP.
.br
.SH SEE ALSO
makess(3), rjustify(3), pad(3), trim(3).
.br
