.TH TRIM 3 "12 September 1995"
.FB
.SH NAME
trim \- trim a string
.SH SYNOPSIS
char *fb_trim(s)
.br
char *s;
.PP
.SH DESCRIPTION
\fIFb_trim\fP is a simple routine in the \fIFirstBase\fP library used to
remove trailing blanks from any NULL terminated string.
.PP
\fIFb_trim\fP returns the argument \fIs\fP.
.br
.SH SEE ALSO
makess(3), rjustify(3), pad(3).
.br
