/*
 * Copyright (C) 2001 FirstBase Software, Inc. All rights reserved.
 *
 * $Id: serv_xdr.c,v 9.0 2001/01/09 02:56:36 john Exp $
 *
 * See the file LICENSE for conditions of use and distribution.
 *
 */

#ifndef LINT
static char Fbserver_xdr_sid[] = "@(#) $Id: serv_xdr.c,v 9.0 2001/01/09 02:56:36 john Exp $";
#endif

#if RPC

/*
 * this routine was mostly generated by rpcgen, but i modified it a bit.
 */

#include <fb.h>
#include <fbserver.h>

bool_t fb_xdr_varvec(xdrs, objp)
	XDR *xdrs;
	fb_varvec *objp;
{
        unsigned int len, maxlen;

	if (!xdr_int(xdrs, &objp->v_length)) {
		return (FALSE);
	}
        len = objp->v_length;
        maxlen = 100000000;
        /*
         * Insight says this is an error, and will overwrite memory
         * on the way back ... I think this is not correct.
         * the XDR manual says the memory will be taken care of
         * by the client ...  however, setting maxlen = len
         * does make Insight happy ...
         */
	if (!xdr_bytes(xdrs, (char **)&objp->v_data, &len, maxlen)){
		return (FALSE);
	}
	return (TRUE);
}

#endif /* RPC */
